# Generated by Django 4.2.1 on 2023-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lkapp', '0002_rename_laptops_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
